system:
  port: 18888
  python_bin: "/home/user/PYTHON_PROJECT_ENV/projects/bin/python"
  scripts:
    - mcp_server.py
  mcp_servers:
    - dllb-skill:
        host: '127.0.0.1'
        port: '12345'

discord:
  host: '127.0.0.1'
  port: '18000'
  channel: agenda-task

multiroom:
  python_bin: "/home/user/PYTHON_PROJECT_ENV/projects/bin/python"
  working_dir: "/home/user/ProjectLinux/MultiRoom"